update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,14 +27,19 @@ jobs:
 
       - name: Prepare Jenkins data
         run: |
+          mkdir -p ${{ github.workspace }}/jenkins_backup
           cat ${{ github.workspace }}/jenkins_data/jenkins_backup.tar.gz.part* > ${{ github.workspace }}/jenkins_backup.tar.gz
           md5sum ${{ github.workspace }}/jenkins_backup.tar.gz
 
       - name: Extract Jenkins data and set permission
         run: |
-          mkdir -p ${{ github.workspace }}/jenkins_backup
           tar -xzf ${{ github.workspace }}/jenkins_backup.tar.gz -C ${{ github.workspace }}/jenkins_backup
+          if [ -d "${{ github.workspace }}/jenkins_backup/var/jenkins_home" ]; then
           chmod -R 777 ${{ github.workspace }}/jenkins_backup/var/jenkins_home
+          else
+          echo "Error: Directory ${{ github.workspace }}/jenkins_backup/var/jenkins_home does not exist."
+          exit 1
+          fi
 
       - name: Docker login
         run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
